services:
  postgres:
    image: postgres:latest
    container_name: courtReserve
    environment:
      POSTGRES_DB: court_reserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped